imprimi "oi";
ka verdadi ou ka falsu
si (i =/= 10)
si (i == 10)
si (i <> 10)
super
falsu
funson test() {
     divolvi 20;
}
di 1 ti 10;
timenti (i < 10) imprimi i;
verdadi e falsu
si (i != 10)
e ou 
klasi
si sinou
sinou 
si
mimoria nome = "Alfredo";
mimoria 
cidade = 
"Alfredo";
1 > 1 1 >= 2
1 = 1 
1 == 1
(}){
     +*  / - ;;
     123
0.123
10.3
// Im a comment
 987.27 
"Hello"
"Hello 
world!"
"Ola \n Mundo
!"