
klasi Animal {
    konstrutor(velocidade, distancia) {
        keli.vel = velocidade;
        keli.dis = distancia;
    }
    bua() {}
    anda(distance, speed) {
        imprimi distance * speed;
    }
    dan_velocidade() {
        imprimi "vel = " + keli.vel;
    }
}

mimoria gatu = Animal("69", 10);
gatu.dan_velocidade();
// gatu.velocidade = "10";
// gatu.nomi = "Mimi";
// imprimi gatu.nomi;
// gatu.anda(10, 4);
// gatu.imprimi_velovidade();

// funson Forma_2D() {
//     klasi Forma {}
//     mimoria circulo = Forma();
//     circulo.raio = 5;
//     imprimi circulo.raio; 
// }
// Forma_2D();
